apiVersion: apps/v1
kind: Deployment
metadata:
  name: subha-app-deploy
  labels:
    app: subha-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: subha-app
  template:
    metadata:
      labels:
        app: subha-app
    spec:
      containers:
      - name: subha-app-container
        image: suvo7886/cicd-project:v2
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: subha-app-np-service
  labels:
    app: subha-app
spec:
  selector:
    app: subha-app
  type: NodePort
  ports:
  - nodePort: 31000
    port: 8080
    targetPort: 8080
# ---
# apiVersion: v1
# clusters:
# - cluster:
#     certificate-authority-data: DATA+OMITTED
#     server: https://kubernetes.docker.internal:6443
#   name: docker-desktop
# contexts:
# - context:
#     cluster: docker-desktop
#     user: docker-desktop
#   name: docker-desktop
# current-context: docker-desktop
# kind: Config
# preferences: {}
# users:
# - name: docker-desktop
#   user:
#     client-certificate-data: REDACTED
#     client-key-data: REDACTED
